### ISSUE TITLE
Support Direction.Up

### ISSUE THREAD

**Issue by alexstyl** [alexstyl/compose-tinder-card#1]
Enable swiping Up as a `Direction`

**Comment by AndroidPoet** [comment]
Hi Alex! i have added this functionality,working on final touches

**Comment by alexstyl** [comment]
> Hi Alex! i have added this functionality,working on final touches

The repo is not currently in a stage where it can accept external contributions other than bug fixes. Until the API is stable (1.0.0 release) Im happy with new issues with feedback, suggestions and bug fixes instead.

**Comment by alexstyl** [comment]
This was introduced in [0.1.0](https://github.com/alexstyl/compose-tinder-card/releases/tag/0.1.0). Closing this as done
