### ISSUE TITLE
Concurrent Execution Exception issue

### ISSUE THREAD

**Issue by yagnikv33** [alexstyl/compose-tinder-card#4]
Hello, @alexstyl this is such a good library and I want to inform you that I faced the issue of "concurrent execution exception" which happens when the user continues to swipe too many times. This issue is because the list is modified every time. I am just informing you in case you find a solution then solved it. So that other users don't face the same problem.

**Comment by alexstyl** [comment]
Thanks @yagnikv33. 

Do you have a stacktrace for this? It this a crash coming from the library or a project that uses the library? A code sample would help

**Comment by yagnikv33** [comment]
> Thanks @yagnikv33. 
> 
> Do you have a stacktrace for this? It this a crash coming from the library or a project that uses the library? A code sample would help

Actually, I didn't use this library but the code is similar that I have done so based on that I am wondering that maybe users will face the problem.

**Comment by alexstyl** [comment]
sure thing. kindly open a new issue when you have more info.

closing this for now
